import { StyleSheet } from 'react-native';

const navy = '#12345A';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F5F8FC' },
  homeContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 28,
    justifyContent: 'center',
  },
  topRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 52 },
  logoMark: {
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: navy,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  logoMarkText: { color: '#FFFFFF', fontSize: 23, fontWeight: '800' },
  brandName: { color: navy, fontSize: 22, fontWeight: '800', letterSpacing: -0.7 },
  versionPill: {
    marginLeft: 9,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: '#E6EDF6',
  },
  versionText: { color: '#54708F', fontSize: 9, fontWeight: '800', letterSpacing: 0.8 },
  hero: { marginBottom: 30 },
  eyebrow: {
    color: '#16866F',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.7,
    marginBottom: 13,
  },
  heading: { color: navy, fontSize: 39, lineHeight: 46, fontWeight: '800', letterSpacing: -1.1 },
  intro: { color: '#64748B', fontSize: 15, lineHeight: 23, marginTop: 13, maxWidth: 340 },
  browseButton: {
    minHeight: 54,
    borderRadius: 16,
    backgroundColor: '#16866F',
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 13,
    shadowColor: '#14745F',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
    elevation: 2,
  },
  browseButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  browseArrow: { color: '#FFFFFF', fontSize: 25, marginLeft: 9, marginTop: -2 },
  options: { gap: 14 },
  optionCard: {
    minHeight: 104,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 17,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8EEF5',
    shadowColor: '#18385C',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 2,
  },
  optionCardGreen: { borderColor: '#DDEFEA' },
  iconCircle: {
    width: 52,
    height: 52,
    borderRadius: 17,
    backgroundColor: '#EAF1FA',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  iconCircleGreen: { backgroundColor: '#E7F5F0' },
  optionIcon: { fontSize: 23 },
  optionCopy: { flex: 1 },
  optionTitle: { color: navy, fontSize: 17, fontWeight: '750', marginBottom: 5 },
  optionDescription: { color: '#718096', fontSize: 12, lineHeight: 17 },
  arrow: { color: '#91A1B5', fontSize: 30, marginLeft: 6, marginTop: -3 },
  footer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 27 },
  footerDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#29A789', marginRight: 8 },
  footerText: { color: '#8391A3', fontSize: 12, fontWeight: '500' },
  placeholderScreen: { flex: 1, padding: 24, justifyContent: 'center', alignItems: 'center' },
  backButton: {
    position: 'absolute',
    top: 20,
    left: 24,
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: { color: navy, fontSize: 34, lineHeight: 38, marginTop: -4 },
  placeholderIcon: {
    width: 84,
    height: 84,
    borderRadius: 27,
    backgroundColor: '#EAF1FA',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 23,
  },
  placeholderEmoji: { fontSize: 36 },
  placeholderTitle: { color: navy, fontSize: 27, fontWeight: '800', marginBottom: 10 },
  placeholderDescription: { color: '#64748B', fontSize: 15, lineHeight: 23, textAlign: 'center', maxWidth: 290 },
  homeButton: {
    backgroundColor: navy,
    minHeight: 52,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 27,
  },
  homeButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
});
