import { StyleSheet } from 'react-native';

export const detailStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F5F8FC' },
  content: { flexGrow: 1, paddingHorizontal: 21, paddingTop: 15, paddingBottom: 18 },
  header: { flexDirection: 'row', alignItems: 'center', marginBottom: 23 },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8EEF5',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 13,
  },
  backText: { color: '#12345A', fontSize: 32, lineHeight: 36, marginTop: -3 },
  headerTitle: { color: '#12345A', fontSize: 22, fontWeight: '800' },
  headerSubtitle: { color: '#718096', fontSize: 13, marginTop: 3 },
  body: { flex: 1 },
  heroCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E7EDF4',
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
  },
  title: { color: '#12345A', fontSize: 24, lineHeight: 31, fontWeight: '800' },
  subtitle: { color: '#16866F', fontSize: 15, fontWeight: '700', marginTop: 5 },
  location: { color: '#718096', fontSize: 13, marginTop: 10 },
  pay: { color: '#14745F', fontSize: 18, fontWeight: '800', marginTop: 15 },
  section: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E7EDF4',
    borderRadius: 18,
    padding: 17,
    marginBottom: 14,
  },
  sectionTitle: { color: '#12345A', fontSize: 15, fontWeight: '800', marginBottom: 12 },
  field: { marginBottom: 11 },
  fieldLabel: { color: '#8997A8', fontSize: 11, fontWeight: '700', marginBottom: 3 },
  fieldValue: { color: '#425970', fontSize: 14, lineHeight: 21 },
  areas: { color: '#425970', fontSize: 14, lineHeight: 22 },
  callButton: {
    minHeight: 56,
    borderRadius: 17,
    backgroundColor: '#16866F',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
    shadowColor: '#14745F',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.17,
    shadowRadius: 9,
    elevation: 3,
  },
  callIcon: { color: '#FFFFFF', fontSize: 18, marginRight: 9 },
  callText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  emptyText: { color: '#718096', fontSize: 15, textAlign: 'center', lineHeight: 22 },
});
