import { StyleSheet } from 'react-native';

export const formStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F5F8FC' },
  keyboard: { flex: 1 },
  content: { paddingHorizontal: 21, paddingTop: 15, paddingBottom: 30 },
  introCard: {
    borderRadius: 17,
    backgroundColor: '#EAF1FA',
    paddingHorizontal: 15,
    paddingVertical: 13,
    marginBottom: 22,
    flexDirection: 'row',
    alignItems: 'center',
  },
  introMark: {
    width: 32,
    height: 32,
    borderRadius: 11,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 11,
  },
  introMarkText: { color: '#12345A', fontSize: 18, fontWeight: '800' },
  introText: { flex: 1, color: '#4E647E', fontSize: 12, lineHeight: 18 },
  sectionLabel: {
    color: '#16866F',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    marginTop: 2,
    marginBottom: 14,
  },
  labelLike: { color: '#263B54', fontSize: 13, fontWeight: '700', marginBottom: 8 },
  choiceRow: { flexDirection: 'row', gap: 10, marginBottom: 18 },
  choice: {
    flex: 1,
    minHeight: 47,
    borderWidth: 1,
    borderColor: '#DCE5EF',
    borderRadius: 13,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  choiceSelected: { backgroundColor: '#E7F5F0', borderColor: '#29A789' },
  choiceText: { color: '#66788D', fontSize: 14, fontWeight: '700' },
  choiceTextSelected: { color: '#14745F' },
  note: { color: '#7B8999', fontSize: 12, lineHeight: 18, textAlign: 'center', marginBottom: 6 },
});
