import { StyleSheet } from 'react-native';

export const listingStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F5F8FC' },
  content: { flex: 1, paddingHorizontal: 20, paddingTop: 14 },
  header: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8EEF5',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  backText: { color: '#12345A', fontSize: 30, lineHeight: 34, marginTop: -3 },
  headerTitle: { color: '#12345A', fontSize: 23, fontWeight: '800' },
  headerSubtitle: { color: '#718096', fontSize: 12, marginTop: 3 },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#E9EFF6',
    borderRadius: 16,
    padding: 4,
    marginBottom: 15,
  },
  tab: {
    flex: 1,
    minHeight: 53,
    paddingHorizontal: 8,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeTab: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#12345A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    elevation: 2,
  },
  tabText: { color: '#68798D', fontSize: 12, lineHeight: 16, fontWeight: '700', textAlign: 'center' },
  activeTabText: { color: '#12345A' },
  resultCount: { color: '#8190A1', fontSize: 12, marginBottom: 11 },
  errorBox: {
    backgroundColor: '#FFF4E5',
    borderRadius: 13,
    paddingHorizontal: 13,
    paddingVertical: 11,
    marginBottom: 12,
  },
  errorText: { color: '#875B1B', fontSize: 12, lineHeight: 18 },
  retryButton: { alignSelf: 'flex-start', paddingTop: 8 },
  retryText: { color: '#12345A', fontSize: 12, fontWeight: '800' },
  loading: { marginTop: 32 },
  listContent: { paddingBottom: 24 },
  card: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E7EDF4',
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#18385C',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.045,
    shadowRadius: 9,
    elevation: 1,
  },
  cardTop: { flexDirection: 'row', alignItems: 'flex-start' },
  cardTitleBlock: { flex: 1, paddingRight: 8 },
  cardTitle: { color: '#12345A', fontSize: 17, lineHeight: 22, fontWeight: '800' },
  businessName: { color: '#718096', fontSize: 13, marginTop: 3 },
  payBadge: {
    backgroundColor: '#E7F5F0',
    borderRadius: 11,
    paddingHorizontal: 10,
    paddingVertical: 7,
    alignItems: 'flex-end',
  },
  payValue: { color: '#14745F', fontSize: 13, fontWeight: '800' },
  payPeriod: { color: '#4D8C7B', fontSize: 10, marginTop: 2 },
  divider: { height: 1, backgroundColor: '#EDF1F5', marginVertical: 12 },
  metaRow: { flexDirection: 'row', alignItems: 'center' },
  locationDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#29A789', marginRight: 7 },
  metaText: { color: '#596D82', fontSize: 13 },
  occupation: { color: '#16866F', fontSize: 13, fontWeight: '700', marginTop: 5 },
  workerMeta: { color: '#718096', fontSize: 12, marginTop: 9 },
  areaText: { color: '#596D82', fontSize: 12, lineHeight: 18, marginTop: 8 },
  cardAction: { color: '#16866F', fontSize: 12, fontWeight: '800', marginTop: 13 },
  emptyText: { color: '#718096', fontSize: 14, textAlign: 'center', marginTop: 30 },
});
