import { StyleSheet } from 'react-native';

export const componentStyles = StyleSheet.create({
  field: { marginBottom: 17 },
  label: { color: '#263B54', fontSize: 13, fontWeight: '700', marginBottom: 8 },
  input: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: '#E0E7EF',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 15,
    paddingVertical: 13,
    color: '#183653',
    fontSize: 15,
  },
  multilineInput: { minHeight: 104, paddingTop: 14 },
  header: { flexDirection: 'row', alignItems: 'center', marginBottom: 23 },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 13,
    borderWidth: 1,
    borderColor: '#E8EEF5',
  },
  backButtonText: { color: '#12345A', fontSize: 32, lineHeight: 36, marginTop: -3 },
  headerCopy: { flex: 1 },
  headerTitle: { color: '#12345A', fontSize: 22, lineHeight: 28, fontWeight: '800' },
  headerSubtitle: { color: '#718096', fontSize: 13, lineHeight: 19, marginTop: 3 },
  publishButton: {
    minHeight: 54,
    borderRadius: 16,
    backgroundColor: '#12345A',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
    marginBottom: 22,
    shadowColor: '#12345A',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.16,
    shadowRadius: 9,
    elevation: 3,
  },
  publishButtonDisabled: { opacity: 0.62 },
  publishButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
});
